<?php

namespace App\Models;

use App\Models\Scopes\IsActiveScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
    protected $primaryKey = 'id';
    protected $keyType = 'string';
    public $incrementing = false;
    public $timestamps = false;

    protected static function booted()
    {
        parent::booted();
        self::addGlobalScope(new IsActiveScope());// TODO: Change the autogenerated stub
    }


    protected $fillable = [
        'id',
        'name',
        'description'
    ];


}
